create OR REPLACE PROCEDURE DELETEROVER (RID IN NUMBER)
IS
  BEGIN
    DELETE FROM ROVERMAP WHERE ROVERID=RID;
    DELETE FROM TASK WHERE OBJECTIVEID IN(SELECT OBJECTIVEID FROM OBJECTIVE WHERE COMPUTERID=(SELECT COMPUTERID FROM ROVERCOMPUTER WHERE ROVERID=(RID)));
    DELETE FROM OBJECTIVE WHERE COMPUTERID IN(SELECT COMPUTERID FROM ROVERCOMPUTER WHERE ROVERID=(RID));
    DELETE FROM ROVERCOMPUTER WHERE ROVERID=RID;
    DELETE FROM CAMERA WHERE ROVERID=RID;
    DELETE FROM INSTRUMENT WHERE ROVERID=RID;
    DELETE FROM SENSOR WHERE ROVERID=RID;
    DELETE FROM ROVER WHERE ROVERID=RID;
  END;
/


